#!/usr/bin/env node
/**
 * 1. process.argv[2]の代わりに[1]も使えます。
 *
 * ターミナルではこれになりました
 * ```
 *   $ ./app
 *   $ ./app -f ../g
 *   $ ./app -t hi 
 * ```
 */

var path = require("path"),
	command = process.argv[2];

if(command == "-f") {
	var file = process.argv[3];
	require("child_process").exec("say-more -f "+file);
} else if(command == "-t") {
	var text = process.argv[3];
	require("child_process").exec("say-more -t "+text);
} else {
	console.info("app -f [file] or app -t [text]");
}