#!/usr/bin/env node
/**
 * 1. process.argvを使うよりyargsの法が簡単です。
 *
 * ターミナルではこれになりました
 * ```
 *   $ ./app
 *   $ ./app -f ../i -c=3
 * ```
 */
var yargs = require("yargs")
	    .usage('Usage: app -f [file]')
	    .describe('f', 'Load a file')
	    .describe('c', 'Counts the files')
	    .alias("file", "f")
	    .alias("count", "c")
	    .default('c', 1),
	async = require("async"),
	argv = yargs.argv;

if(argv.f) {
	async.timesSeries(argv.c || 1, function(n, next) {
		require("child_process").exec("say-more -f "+argv.f, next);
	}, function() {
		require("child_process").exec("say-more -f ../i2");
	});
} else {
	yargs.showHelp();
}